on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

name: linting

jobs:
  lintr:
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v2
      - uses: r-lib/actions/setup-r@master
      - name: Install dependencies
        run: |
          install.packages(c("remotes", "rcmdcheck", "lintr"))
          remotes::install_deps(dependencies = TRUE)
        shell: Rscript {0}
      - name: Lint
        run: |
          out <- lintr::lint_package()
          print(out)
          if (length(out)) stop("linting errors found")
        shell: Rscript {0}
